# Generated by Django 5.2.13 on 2026-04-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExampleBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("block_type", models.CharField(default="field", max_length=50)),
                ("num_beds", models.IntegerField(default=0)),
                (
                    "bed_width_feet",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("bedfeet_per_bed", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ExampleCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("crop_type", models.CharField(blank=True, default="", max_length=100)),
            ],
        ),
    ]
