# Generated by Django 5.2.14 on 2026-05-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleFarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                ("established_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExampleVariety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "seed_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("full_description", models.TextField(blank=True, default="")),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="varieties",
                        to="examples.examplecrop",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="varieties",
                        to="examples.examplefarm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExampleField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "acreage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examples.examplefarm",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "farm")},
            },
        ),
    ]
