# Generated by Django 5.2.13 on 2026-04-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deployment", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="releaserecord",
            new_name="deployment__space_704c54_idx",
            old_name="deployment__space_3b83f5_idx",
        ),
        migrations.RenameIndex(
            model_name="releaserecord",
            new_name="deployment__space_423334_idx",
            old_name="deployment__space_752230_idx",
        ),
    ]
