"""Shared utilities for rendering Python source code from contract data."""

from __future__ import annotations

import json
from typing import Any


def render_choices_class(name: str, pairs: list[tuple[str, str]]) -> str:
    """Render a ``models.TextChoices`` class.

    Args:
        name: Enum class name (e.g. ``"EventType"``).
        pairs: List of ``(value, label)`` tuples.

    Returns:
        Source block for the choices class.
    """
    lines = [
        "",
        f"class {name}(models.TextChoices):",
    ]
    for value, label in pairs:
        key = value.upper().replace(" ", "_")
        lines.append(f'    {key} = {value!r}, {label!r}')
    lines.append("")
    return "\n".join(lines)


def render_field_kwargs(
    kwargs: dict[str, Any],
    enum_names: set[str] | None = None,
    model_name: str | None = None,
) -> str:
    """Render a Django field kwargs dict as a Python keyword-argument string.

    Args:
        kwargs: Keyword arguments for a Django model field constructor.
        enum_names: Set of known enum type names; when ``choices`` matches one,
            it is rendered as a model-qualified reference.
        model_name: The Django model class name (needed when rendering choices
            as ``<ModelName>.<EnumName>``).

    Returns:
        Comma-separated ``key=value`` string, e.g.
        ``"max_length=200, unique=True, blank=True"``.

    ``on_delete`` values are always rendered as Django attribute references
    (``models.PROTECT``).  The ``to`` key is NOT handled here — it is the
    caller's responsibility (see :func:`render_field`) so that ForeignKey
    fields can render the target as a positional argument.
    """
    parts: list[str] = []
    for k, v in kwargs.items():
        if k is None:
            parts.append(f"null={v}")
        elif k == "on_delete":
            raw = str(v).removeprefix("models.")
            parts.append(f"on_delete=models.{raw}")
        elif k == "choices" and enum_names and isinstance(v, str):
            enum_name = v.removesuffix(".choices") if v.endswith(".choices") else v
            if enum_name in enum_names:
                parts.append(f"choices={enum_name}.choices")
            else:
                parts.append(f"{k}={v!r}")
        elif isinstance(v, bool):
            parts.append(f"{k}={v}")
        elif isinstance(v, int):
            parts.append(f"{k}={v}")
        elif v is None:
            parts.append(f"{k}=None")
        else:
            parts.append(f"{k}={v!r}")
    return ", ".join(parts)


def render_field(
    name: str,
    field_class: str,
    kwargs: dict[str, Any],
    indent: int = 4,
    enum_names: set[str] | None = None,
    model_name: str | None = None,
    rendered_model_names: set[str] | None = None,
) -> str:
    """Render a single Django model field declaration.

    Args:
        name: Field name (e.g. ``"crop"``).
        field_class: Fully-qualified Django field class (e.g. ``"models.ForeignKey"``).
        kwargs: Keyword arguments for the field constructor.
        indent: Spaces of indentation (default 4).
        enum_names: Set of known enum type names (passed to *render_field_kwargs*).
        model_name: The Django model class name (for enum references).
        rendered_model_names: Set of already-rendered model names; used to
            detect forward references that need quoting.

    Returns:
        Indented field declaration line::

            name = models.CharField(max_length=200, unique=True)
    """
    pad = " " * indent

    if field_class == "models.ForeignKey":
        remaining = dict(kwargs)
        to_val = remaining.pop("to", None)
        kw_str = render_field_kwargs(remaining, enum_names, model_name)
        if to_val is not None:
            if isinstance(to_val, str) and to_val == "self":
                to_str = '"self"'
            elif isinstance(to_val, str) and to_val.isidentifier() and rendered_model_names is not None and to_val not in rendered_model_names:
                to_str = repr(to_val)
            elif isinstance(to_val, str) and to_val.isidentifier():
                to_str = to_val
            else:
                to_str = repr(to_val)
            body = f"{to_str}, {kw_str}" if kw_str else to_str
        else:
            body = kw_str
    else:
        body = render_field_kwargs(kwargs, enum_names, model_name)

    if body:
        return f"{pad}{name} = {field_class}({body})"
    return f"{pad}{name} = {field_class}()"


def render_import_block(
    app_label: str,
    extra_imports: list[str] | None = None,
) -> str:
    """Render the module-level imports for a generated ``models.py``.

    Args:
        app_label: App label (used in header comment only).
        extra_imports: Additional import lines (e.g. ``["from django.conf import settings"]``).

    Returns:
        Import block string ending with a trailing newline.
    """
    lines: list[str] = [
        "# Generated by migration-workbench codegen — hand-editable",
        f"# App label: {app_label}",
        "# Last generated: see git history",
        "",
        "from django.db import models",
    ]
    if extra_imports:
        lines.extend(extra_imports)
    lines.append("")
    return "\n".join(lines)


def render_computed_property(
    name: str,
    return_type: str | None = None,
    expression: str | None = None,
    indent: int = 4,
) -> str:
    """Render a ``@property`` method from a computed field definition.

    Args:
        name: Property name (e.g. ``"signed_quantity"``).
        return_type: Optional return type annotation.
        expression: Python source for the property body.  When ``None``,
            renders a stub with ``...``.
        indent: Spaces of indentation (default 4).

    Returns:
        Property method source block.
    """
    pad = " " * indent
    lines: list[str] = []
    lines.append(f"{pad}@property")
    if return_type:
        lines.append(f"{pad}def {name}(self) -> {return_type}:")
    else:
        lines.append(f"{pad}def {name}(self):")
    if expression:
        for line in expression.strip().split("\n"):
            lines.append(f"{pad * 2}{line}")
    else:
        lines.append(f"{pad * 2}...")
    lines.append("")
    return "\n".join(lines)


def render_str_method(template: str | None, indent: int = 4) -> str:
    """Render ``def __str__`` method.

    Args:
        template: f-string template body (e.g. ``"{self.name}"``), or ``None``
            to skip rendering.
        indent: Spaces of indentation (default 4).

    Returns:
        Method source block, or an empty string when *template* is ``None``.
    """
    if not template:
        return ""
    pad = " " * indent
    return (
        f"{pad}def __str__(self):\n"
        f'{pad * 2}return f"{template}"\n'
    )


def _render_meta_value(k: str, v: Any, inner: str) -> str:
    """Render a single Meta option value."""
    if k in ("indexes", "constraints"):
        return ""  # handled separately below
    if isinstance(v, str):
        return f'{inner}{k} = "{v}"'
    if isinstance(v, bool):
        return f"{inner}{k} = {v}"
    if isinstance(v, int):
        return f"{inner}{k} = {v}"
    if v is None:
        return f"{inner}{k} = None"
    if isinstance(v, list) and all(isinstance(item, str) for item in v):
        items = ", ".join(json.dumps(item) for item in v)
        return f"{inner}{k} = [{items}]"
    return f"{inner}{k} = {v!r}"


def _render_index(idx: dict[str, Any], inner: str) -> str:
    """Render a ``models.Index(...)`` declaration."""
    fields = idx.get("fields", [])
    fields_str = ", ".join(repr(f) for f in fields)
    name = idx.get("name")
    if name:
        return f"{inner}models.Index(fields=[{fields_str}], name={name!r}),"
    return f"{inner}models.Index(fields=[{fields_str}]),"


def _render_constraint(con: dict[str, Any], inner: str) -> str:
    """Render a ``models.UniqueConstraint(...)`` declaration."""
    fields = con.get("fields", [])
    fields_str = ", ".join(repr(f) for f in fields)
    name = con.get("name", "")
    return f"{inner}models.UniqueConstraint(fields=[{fields_str}], name={name!r}),"


def render_meta(model_meta: dict[str, Any], indent: int = 4) -> str:
    """Render ``class Meta`` block.

    Args:
        model_meta: Options dict (``verbose_name``, ``ordering``, etc.).
            Supports ``indexes`` and ``constraints`` keys with lists of dicts.
        indent: Spaces of indentation (default 4).

    Returns:
        Meta block string, or empty string if *model_meta* is empty.
    """
    if not model_meta:
        return ""
    pad = " " * indent
    inner = " " * (indent * 2)
    lines = [f"{pad}class Meta:"]
    for k, v in model_meta.items():
        if k == "indexes" and isinstance(v, list):
            if v:
                lines.append(f"{inner}indexes = [")
                for idx in v:
                    lines.append(_render_index(idx, inner + "    "))
                lines.append(f"{inner}]")
        elif k == "constraints" and isinstance(v, list):
            if v:
                lines.append(f"{inner}constraints = [")
                for con in v:
                    lines.append(_render_constraint(con, inner + "    "))
                lines.append(f"{inner}]")
        else:
            line = _render_meta_value(k, v, inner)
            if line:
                lines.append(line)
    lines.append("")
    return "\n".join(lines)
