"""Shared utilities for rendering Python source code from contract data."""

from __future__ import annotations

import json
from typing import Any


def render_field_kwargs(kwargs: dict[str, Any]) -> str:
    """Render a Django field kwargs dict as a Python keyword-argument string.

    Args:
        kwargs: Keyword arguments for a Django model field constructor.

    Returns:
        Comma-separated ``key=value`` string, e.g.
        ``"max_length=200, unique=True, blank=True"``.

    ``on_delete`` values are always rendered as Django attribute references
    (``models.PROTECT``).  The ``to`` key is NOT handled here — it is the
    caller's responsibility (see :func:`render_field`) so that ForeignKey
    fields can render the target as a positional argument.
    """
    parts: list[str] = []
    for k, v in kwargs.items():
        if k == "on_delete":
            raw = str(v).removeprefix("models.")
            parts.append(f"on_delete=models.{raw}")
        elif isinstance(v, bool):
            parts.append(f"{k}={v}")
        elif isinstance(v, int):
            parts.append(f"{k}={v}")
        elif v is None:
            parts.append(f"{k}=None")
        else:
            parts.append(f"{k}={v!r}")
    return ", ".join(parts)


def render_field(name: str, field_class: str, kwargs: dict[str, Any], indent: int = 4) -> str:
    """Render a single Django model field declaration.

    Args:
        name: Field name (e.g. ``"crop"``).
        field_class: Fully-qualified Django field class (e.g. ``"models.ForeignKey"``).
        kwargs: Keyword arguments for the field constructor.
        indent: Spaces of indentation (default 4).

    Returns:
        Indented field declaration line::

            name = models.CharField(max_length=200, unique=True)
    """
    pad = " " * indent

    if field_class == "models.ForeignKey":
        remaining = dict(kwargs)
        to_val = remaining.pop("to", None)
        kw_str = render_field_kwargs(remaining)
        if to_val is not None:
            to_str = to_val if isinstance(to_val, str) and to_val.isidentifier() else repr(to_val)
            body = f"{to_str}, {kw_str}" if kw_str else to_str
        else:
            body = kw_str
    else:
        body = render_field_kwargs(kwargs)

    if body:
        return f"{pad}{name} = {field_class}({body})"
    return f"{pad}{name} = {field_class}()"


def render_import_block(
    app_label: str,
    extra_imports: list[str] | None = None,
) -> str:
    """Render the module-level imports for a generated ``models.py``.

    Args:
        app_label: App label (used in header comment only).
        extra_imports: Additional import lines (e.g. ``["from django.conf import settings"]``).

    Returns:
        Import block string ending with a trailing newline.
    """
    lines: list[str] = [
        "# Generated by migration-workbench codegen — hand-editable",
        f"# App label: {app_label}",
        "# Last generated: see git history",
        "",
        "from django.db import models",
    ]
    if extra_imports:
        lines.extend(extra_imports)
    lines.append("")
    return "\n".join(lines)


def render_str_method(template: str | None, indent: int = 4) -> str:
    """Render ``def __str__`` method.

    Args:
        template: f-string template body (e.g. ``"{self.name}"``), or ``None``
            to skip rendering.
        indent: Spaces of indentation (default 4).

    Returns:
        Method source block, or an empty string when *template* is ``None``.
    """
    if not template:
        return ""
    pad = " " * indent
    return (
        f"{pad}def __str__(self):\n"
        f'{pad * 2}return f"{template}"\n'
    )


def render_meta(model_meta: dict[str, Any], indent: int = 4) -> str:
    """Render ``class Meta`` block.

    Args:
        model_meta: Options dict (``verbose_name``, ``ordering``, etc.).
        indent: Spaces of indentation (default 4).

    Returns:
        Meta block string, or empty string if *model_meta* is empty.
    """
    if not model_meta:
        return ""
    pad = " " * indent
    inner = " " * (indent * 2)
    lines = [f"{pad}class Meta:"]
    for k, v in model_meta.items():
        if isinstance(v, str):
            lines.append(f'{inner}{k} = "{v}"')
        elif isinstance(v, list):
            items = ", ".join(json.dumps(item) for item in v)
            lines.append(f"{inner}{k} = [{items}]")
        elif isinstance(v, bool):
            lines.append(f"{inner}{k} = {v}")
        elif v is None:
            lines.append(f"{inner}{k} = None")
        else:
            lines.append(f"{inner}{k} = {v!r}")
    lines.append("")
    return "\n".join(lines)
